CREATE TABLE tb_artist(
	artist_id SMALLINT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	artist_name CHAR(128) NOT NULL
);

CREATE TABLE tb_album(
	album_id SMALLINT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	artist_id SMALLINT(4) NOT NULL,
	album_name CHAR(128) NOT NULL,
	FOREIGN KEY (artist_id) REFERENCES tb_artist(artist_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE tb_track(
	track_id SMALLINT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	track_name CHAR(128) NOT NULL,
	artist_id SMALLINT(5) NOT NULL,
	album_id SMALLINT(4) NOT NULL,
	waktu DECIMAL(5,2)
);

CREATE TABLE tb_played(
	played_id SMALLINT(3) NOT NULL  AUTO_INCREMENT PRIMARY KEY,
	artist_id SMALLINT(5) NOT NULL,
	album_id SMALLINT(4) NOT NULL,
	track_id SMALLINT(3),
	played TIMESTAMP
);
